# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Load Test action step
      id: load-test
      uses: kenju/github-actions-artillery@master
      with:
        filepath: ./src/__tests__/load/load-test.yml
          
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install     
      
    - name: Create env file 
      run: |
        touch .env
        echo REACT_APP_OPENWEATHER_API_KEY="e2a9f3d7993c0b9d5043b663318059c4" >> .env
        echo SKIP_PREFLIGHT_CHECK="true" >> .env
        cat .env
        
    - name: Run test
      run: npm run test 
      
    - name: Build
      run: CI='' npm run build
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        
    - name: End2End Cypress run
      uses: cypress-io/github-action@v2      
    
      
